services:
  database:
    image: mongo:6.0
    restart: unless-stopped
    env_file: ".env"
    volumes:
      - ./mongoData:/data/db
    ports:
      - "27035:27017"
  keydb:
    image: eqalpha/keydb
    command: keydb-server /etc/keydb/keydb.conf --server-threads 2
    ports:
      - "6379:6379"
    volumes:
      - ./keydb.conf:/etc/keydb/keydb.conf
      - ./data-keydb:/data
  web:
    image: australia-southeast1-docker.pkg.dev/redfur/adastral/cockatoo-webapi:latest
    build: .
    restart: unless-stopped
    env_file: ".env"
    volumes:
      - ./data:/app/data
    ports:
      - "9870:80"
    depends_on:
      - database
      - keydb
    sysctl:
      - fs.inotify.max_user_instances=524288